### ISSUE TITLE
This emits warnings for Unicode strings that contain the non-breaking space character

### ISSUE THREAD

**Issue by robrwo** [jhannah/pdf-textblock#1]
When inserting a text block with strings that contain the Unicode "non-breaking space" character 0x00A0, it emits warnings:

```
Use of uninitialized value in addition (+) at /usr/local/lib/perl/5.10.1/PDF/TextBlock.pm line 377.
Use of uninitialized value in addition (+) at /usr/local/lib/perl/5.10.1/PDF/TextBlock.pm line 376.
```

**Comment by jhannah** [comment]
I'm not seeing these warnings in version 0.07: https://github.com/jhannah/pdf-textblock/blob/master/t/50-demo.t#L22

If you are seeing them, please let me know. Thanks! :)

**Comment by robrwo** [comment]
I'm no longer working on that project, so I'm not in a position to test it.
