### ISSUE TITLE
PAUSE tarball failed to include new t/ files

### ISSUE THREAD

**Issue by jhannah** [jhannah/pdf-textblock#8]
https://rt.cpan.org/Public/Bug/Display.html?id=134031
@PhilterPaper wrote:
> Although 5 new t-tests (11-demo.t, 21-demo.t, 31-demo.t, 41-demo.t, and 51-demo.t) are in GitHub, your build failed to include them in the CPAN build package. These are all tests specific to PDF::Builder usage, rather than trying to switch between PDF::API2 and PDF::Builder on the fly. The x0-demo.t tests still test PDF::API2.

Whoops! Sorry. Fixing.

**Comment by jhannah** [comment]
@PhilterPaper Fixed in 0.13 which has been pushed to PAUSE. Please confirm at your convenience. :)

**Comment by PhilterPaper** [comment]
0.13 is on CPAN and installs cleanly. OK to close this ticket. Thank you for your prompt attention to this.
